### ISSUE TITLE
Nothing in the clipboard history

### ISSUE THREAD

**Issue by ms6000** [lunu-bounir/clipboard-helper#1]
Hi

Was delighted to find your addon as it should do exactly what I want, but...

I ran the install.bat see nothing when I ctrl+C or any other method of adding to the clipboard

![image](https://user-images.githubusercontent.com/30551294/51112482-adfddd00-17f6-11e9-8111-4efd83abdb02.png)

Hope we can fix it as I really need this and want to give you five stars!

m

**Comment by lunu-bounir** [comment]
sorry for the late reply. It seems like I've been unwatched from my own project! Do you still have the issue? Do you get any error inside the browser console?

**Comment by ms6000** [comment]
Hi Lunu

 

No problem, glad to hear from you. But sorry to say I have uninstalled your app and am using the native Windows Clipboard now that it has a ‘memory’.

 

Cheers

 

m
